const LAUNCHBOX_CONSOLES_MAPPING = {
  "3do": "3DO Interactive Multiplayer",
  "aamberpegasus": "Aamber Pegasus",
  "archimedes": "Acorn Archimedes",
  "atom": "Acorn Atom",
  "electron": "Acorn Electron",
  "cpc": "Amstrad CPC",
  "gx4000": "Amstrad GX4000",
  "android": "Android",
  "apfm1000": "APF Imagination Machine",
  "bk01": "Apogee BK-01",
  "appleii": "Apple II",
  "appleiigs": "Apple IIGS",
  "ios": "Apple iOS",
  "macos": "Apple Mac OS",
  "arcade": "Arcade",
  "arduboy": "Arduboy",
  "atari2600": "Atari 2600",
  "atari5200": "Atari 5200",
  "atari7800": "Atari 7800",
  "atari800": "Atari 800",
  "jaguar": "Atari Jaguar",
  "jaguarcd": "Atari Jaguar CD",
  "lynx": "Atari Lynx",
  "atarist": "Atari ST",
  "xegs": "Atari XEGS",
  "astrocade": "Bally Astrocade",
  "sv8000": "Bandai Super Vision 8000",
  "bbcmicro": "BBC Microcomputer System",
  "camputerslynx": "Camputers Lynx",
  "casioloopy": "Casio Loopy",
  "pv1000": "Casio PV-1000",
  "adam": "Coleco ADAM",
  "coleco": "ColecoVision",
  "c128": "Commodore 128",
  "c64": "Commodore 64",
  "amiga": "Commodore Amiga",
  "amigacd32": "Commodore Amiga CD32",
  "cdtv": "Commodore CDTV",
  "maxmachine": "Commodore MAX Machine",
  "pet": "Commodore PET",
  "plus4": "Commodore Plus 4",
  "vic20": "Commodore VIC-20",
  "dragon32": "Dragon 32/64",
  "colourgenie": "EACA EG2000 Colour Genie",
  "elektor": "Elektor TV Games Computer",
  "bk0010": "Elektronika BK",
  "arcadia": "Emerson Arcadia 2001",
  "enterprise": "Enterprise",
  "adventurevision": "Entex Adventure Vision",
  "gamepocket": "Epoch Game Pocket Computer",
  "scv": "Epoch Super Cassette Vision",
  "exl100": "Exelvision EXL 100",
  "sorcerer": "Exidy Sorcerer",
  "channelf": "Fairchild Channel F",
  "fm7": "Fujitsu FM-7",
  "fmtowns": "Fujitsu FM Towns Marty",
  "supracan": "Funtech Super Acan",
  "gp32": "GamePark GP32",
  "gamewave": "GameWave",
  "gamewavefes": "Game Wave Family Entertainment System",
  "vectrex": "GCE Vectrex",
  "gamemaster": "Hartung Game Master",
  "hector": "Hector HRX",
  "vc4000": "Interton VC 4000",
  "jupiterace": "Jupiter Ace",
  "linux": "Linux",
  "odyssey": "Magnavox Odyssey",
  "odyssey2": "Magnavox Odyssey 2",
  "alice": "Matra and Hachette Alice",
  "aquarius": "Mattel Aquarius",
  "hyperscan": "Mattel HyperScan",
  "intellivision": "Mattel Intellivision",
  "megaduck": "Mega Duck",
  "mtx": "Memotech MTX512",
  "msx": "Microsoft MSX",
  "msx2": "Microsoft MSX2",
  "msx2plus": "Microsoft MSX2+",
  "xbox": "Microsoft Xbox",
  "xbox360": "Microsoft Xbox 360",
  "xboxone": "Microsoft Xbox One",
  "xboxseries": "Microsoft Xbox Series X/S",
  "dos": "MS-DOS",
  "mugen": "MUGEN",
  "namcos22": "Namco System 22",
  "pc88": "NEC PC-8801",
  "pc98": "NEC PC-9801",
  "pcfx": "NEC PC-FX",
  "tg16": "NEC TurboGrafx-16",
  "tgcd": "NEC TurboGrafx-CD",
  "3ds": "Nintendo 3DS",
  "n64": "Nintendo 64",
  "n64dd": "Nintendo 64DD",
  "nds": "Nintendo DS",
  "nes": "Nintendo Entertainment System",
  "fds": "Nintendo Famicom Disk System",
  "gb": "Nintendo Game Boy",
  "gba": "Nintendo Game Boy Advance",
  "gbc": "Nintendo Game Boy Color",
  "gc": "Nintendo GameCube",
  "gw": "Nintendo Game & Watch",
  "pokemini": "Nintendo Pokemon Mini",
  "satellaview": "Nintendo Satellaview",
  "switch": "Nintendo Switch",
  "switch2": "Nintendo Switch 2",
  "virtualboy": "Nintendo Virtual Boy",
  "wii": "Nintendo Wii",
  "wiiu": "Nintendo Wii U",
  "ngage": "Nokia N-Gage",
  "nuon": "Nuon",
  "openbor": "OpenBOR",
  "oric": "Oric Atmos",
  "omv": "Othello Multivision",
  "ouya": "Ouya",
  "supergrafx": "PC Engine SuperGrafx",
  "cdi": "Philips CD-i",
  "vg5000": "Philips VG 5000",
  "g7400": "Philips Videopac+",
  "pico8": "PICO-8",
  "pinball": "Pinball",
  "studio2": "RCA Studio II",
  "samcoupe": "SAM Coupé",
  "atomiswave": "Sammy Atomiswave",
  "scummvm": "ScummVM",
  "sega32x": "Sega 32X",
  "segacd": "Sega CD",
  "segacd32x": "Sega CD 32X",
  "dreamcast": "Sega Dreamcast",
  "vmu": "Sega Dreamcast VMU",
  "gamegear": "Sega Game Gear",
  "genesis": "Sega Genesis",
  "hikaru": "Sega Hikaru",
  "master": "Sega Master System",
  "model1": "Sega Model 1",
  "model2": "Sega Model 2",
  "model3": "Sega Model 3",
  "naomi": "Sega Naomi",
  "naomi2": "Sega Naomi 2",
  "pico": "Sega Pico",
  "saturn": "Sega Saturn",
  "sc3000": "Sega SC-3000",
  "sg1000": "Sega SG-1000",
  "stv": "Sega ST-V",
  "system16": "Sega System 16",
  "system32": "Sega System 32",
  "triforce": "Sega Triforce",
  "mz2500": "Sharp MZ-2500",
  "x1": "Sharp X1",
  "x68000": "Sharp X68000",
  "zx81": "Sinclair ZX-81",
  "zxspectrum": "Sinclair ZX Spectrum",
  "neogeo": "SNK Neo Geo AES",
  "neogeocd": "SNK Neo Geo CD",
  "neogeomvs": "SNK Neo Geo MVS",
  "ngp": "SNK Neo Geo Pocket",
  "ngpc": "SNK Neo Geo Pocket Color",
  "psx": "Sony Playstation",
  "ps2": "Sony Playstation 2",
  "ps3": "Sony Playstation 3",
  "ps4": "Sony Playstation 4",
  "ps5": "Sony Playstation 5",
  "vita": "Sony Playstation Vita",
  "pocketstation": "Sony PocketStation",
  "psp": "Sony PSP",
  "pspminis": "Sony PSP Minis",
  "sordm5": "Sord M5",
  "spectravideo": "Spectravideo",
  "snes": "Super Nintendo Entertainment System",
  "typex": "Taito Type X",
  "trs80": "Tandy TRS-80",
  "zodiac": "Tapwave Zodiac",
  "ti99": "Texas Instruments TI 99/4A",
  "gamecom": "Tiger Game.com",
  "tomytutor": "Tomy Tutor",
  "coco": "TRS-80 Color Computer",
  "uzebox": "Uzebox",
  "vector06c": "Vector-06C",
  "creativision": "VTech CreatiVision",
  "socrates": "VTech Socrates",
  "vsmile": "VTech V.Smile",
  "wasm4": "WASM-4",
  "supervision": "Watara Supervision",
  "web": "Web Browser",
  "windows": "Windows",
  "win3x": "Windows 3.X",
  "ws": "WonderSwan",
  "wsc": "WonderSwan Color",
  "actionmax": "WoW Action Max",
  "xavix": "XaviXPORT",
  "zinc": "ZiNc"
};
